apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-reviews-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-reviews
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-reviews
          env:
            - name: POSTGRESQL_USER
              value: dbuser
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: review
          ports:
          - containerPort: 5432
            protocol: TCP